# Generated by Django 4.1.7 on 2023-02-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='task',
            new_name='name',
        ),
    ]
